# Generated by Django 6.0.4 on 2026-04-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REPLIED', 'Replied')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
